apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todo-app
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: todo-app=721912316968.dkr.ecr.us-east-1.amazonaws.com/nodejs-app
    argocd-image-updater.argoproj.io/todo-app.update-strategy: latest
    argocd-image-updater.argoproj.io/todo-app.allow-tags: latest
spec:
  project: default
  source:
    repoURL: https://github.com/Nehad-Said/nodejs-app-devops.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
