apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: todo-app
type: Opaque
data:
  mongodb-uri: bW9uZ29kYitzcnY6Ly9uZWhhZGFiYXNpdDpnc01LR3NWT041amRoTzVlQGNsdXN0ZXIwLmNqNGxsYXUubW9uZ29kYi5uZXQvdG9kb2xpc3REYg==

