apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: todo-app
type: Opaque
data:
  mongodb-uri: bW9uZ29EYlVybCA9IG1vbmdvZGIrc3J2Oi8vbmVoYWRhYmFzaXQ6Z3NNS0dzVk9ONWpkaE81ZUBjbHVzdGVyMC5jajRsbGF1Lm1vbmdvZGIubmV0L3RvZG9saXN0RGI=

