apiVersion: v1
kind: Service
metadata:
  name: todo-app-service
  namespace: todo-app
spec:
  selector:
    app: todo-app
  ports:
  - name: http
    port: 80
    targetPort: 4000
    protocol: TCP
  type: LoadBalancer
