# k8s/todo-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app
  namespace: todo-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      # Add this line to use ECR authentication
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: todo-app
        # Use a specific tag instead of latest for better reliability
        image: 721912316968.dkr.ecr.us-east-1.amazonaws.com/nodejs-app:latest
        ports:
        - containerPort: 4000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-uri
        - name: PORT
          value: "4000"
        - name: NODE_ENV
          value: "production"
        # Temporarily disable health checks until we confirm the app starts
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 4000
        #   initialDelaySeconds: 60
        #   periodSeconds: 10
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 4000
        #   initialDelaySeconds: 30
        #   periodSeconds: 5
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
